LavenderHaze/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings


handler404 = views.handle_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.ghome,name='ghome'),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path('adminpanel/', include('adminpanel.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/',views.signup,name="signup"),
    path('signin/',views.signin,name="signin"),
    path('activate/<uidb64>/<token>/',views.activate,name="activate"),
    path('resetpassword_validate/<uidb64>/<token>/',views.resetpassword_validate,name="resetpassword_validate"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('signout/',views.signout,name="signout"),
    path('forgotPassword/',views.forgotPassword,name="forgotPassword"),
    path('resetPassword/',views.resetPassword,name="resetPassword"),
    path('edit_profile/',views.edit_profile,name="edit_profile"),
    path('my_orders/',views.my_orders,name="my_orders"),
    path('change_password/',views.change_password,name="change_password"),
    path('my_address/',views.my_address,name="my_address"),
    path('add_address/', views.add_address, name='add_address'),
    path('delete_address/<int:id>/', views.delete_address, name='delete_address'),
    path('edit_address/<int:id>/', views.edit_address, name='edit_address'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('user_cancel_order/<int:order_number>/', views.user_cancel_order, name='user_cancel_order'),


]

carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.cart,name='cart'),
    path('add_cart/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart,name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item,name='remove_cart_item'),
    path('checkout',views.checkout,name="checkout"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
# Create your models here.
class MyAccountManager(BaseUserManager):
    def create_user(self,name,email,password=None):
        if not email:
            raise ValueError('User must have an email address')
        if not name:
            raise ValueError('User must have  a name')

        user =   self.model(
            email   =   self.normalize_email(email),
            name    =   name,   
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,name,email,password):
        user = self.create_user(
            email=self.normalize_email(email),
            name= name,
            password=password,
        )
        user.is_admin=True
        user.is_active=True
        user.is_staff=True
        user.is_superadmin=True
        user.save(using=self._db)
        return user

class Account(AbstractBaseUser):
    name    = models.CharField(max_length=50)
    email   =models.EmailField(max_length=100, unique=True)
    phone   =models.CharField(max_length=50)


    date_joined =models.DateTimeField(auto_now_add=True)
    last_login   =models.DateTimeField(auto_now_add=True)
    is_admin    =models.BooleanField(default=False)
    is_staff    =models.BooleanField(default=False)
    is_active    =models.BooleanField(default=False)
    is_superadmin    =models.BooleanField(default=False)


    USERNAME_FIELD='email'
    REQUIRED_FIELDS=['name']

    objects=MyAccountManager()
    
    def __str__(self):
        return self.email

    def has_perm(self,perm,obj=None):
        return self.is_admin

    def has_module_perms(self,add_label):
        return True

class EditProfile(models.Model):
    user = models.OneToOneField(Account,on_delete=models.CASCADE) 
    address_line_1  =   models.CharField(blank=True,max_length=100)
    address_line_2  =   models.CharField(blank=True,max_length=100)
    city    =   models.CharField(blank=True,max_length=20)
    state   =   models.CharField(blank=True,max_length=20)
    country    =   models.CharField(blank=True,max_length=20)


    def __str__(self):
        return self.user.name


    def full_address(self):
        return f'{self.address_line_1},{self.address_line_2}'

accounts/forms.py
from django import forms
from .models import Account,EditProfile
from orders.models import Address

class RegistrationForm(forms.ModelForm):
    

    class Meta:
        model=Account
        fields=['name','email','phone','password']

    
    def __init__(self,*args,**kwargs):
        super(RegistrationForm,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control'})


class UserForm(forms.ModelForm):
    
    class Meta:
        model = Account
        fields =    ('name','phone')

class EditProfileForm(forms.ModelForm): 
    class Meta:
        model = EditProfile
        fields = ('address_line_1','address_line_2','city','state','country')

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields=['name','phone','email','address_line_1','address_line_2','country','state','city']
        
    
    def __init__(self, *args, **kwargs):
      super(AddressForm,self).__init__(*args, **kwargs)  
      for field  in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
             

accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.decorators.cache import cache_control
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm,UserForm,EditProfileForm,AddressForm
from .models import Account,EditProfile
from django.contrib.auth import get_user_model
from LavenderHaze.utils import send_activation_email,send_forgotpassword_mail
from carts.models import Cart,CartItem
from carts.views import _cart_id_
from orders.models import Order,Address, OrderProduct
from store.models import Product
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
from LavenderHaze.settings import RAZOR_KEY_ID,RAZOR_KEY_SECRET
import razorpay
from orders.models import Payment
from django.urls import reverse

from razorpay.errors import BadRequestError
#for email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.shortcuts import HttpResponse
import requests
# Create your views here.

def signup(request):  
    if request.method == 'POST':
        form =   RegistrationForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            phone=form.cleaned_data['phone']
            email=form.cleaned_data['email']
            password=form.cleaned_data['password']

            User    =   get_user_model()
            user= User.objects.create_user(name=name,email=email,password=password)
            # user.phone=phone
            setattr(user, 'phone', phone)
            user.save()
            EditProfile.objects.create(user=user)


            #sending email-helper function in utils
            send_activation_email(request,user)
            messages.success(request, "We have send you an email ,please verify it")
            return redirect('/accounts/signin/?command=verification&email='+email)
    else:
        form   = RegistrationForm()
    context =   {
        'form' : form,
    }
    return render(request,'accounts/signup.html',context)


             
def signin(request):
    if request.method == 'POST':
        email=request.POST['email']
        password=request.POST['password']
        user=authenticate(request,email=email,password=password)
        
        if user is not None:
            try:
                cart    =   Cart.objects.get(cart_id=_cart_id_(request))
                is_cart_item_exists =   CartItem.objects.filter(cart=cart).exists()

                if is_cart_item_exists :
                    cart_item   =   CartItem.objects.filter(cart=cart)
                   
                    for item in cart_item:
                        
                                item.user=  user
                                item.save()
            except:

                pass
            login(request,user)
            url =   request.META.get('HTTP_REFERER')
            try:
                query   =   requests.utils.urlparse(url).query
                params  =   dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage    =   params['next']
                    return redirect(nextPage)
                
                
            except:
                return redirect('ghome')
        else:
            messages.error(request,"Invalid credentials")
            return redirect('signup')
    return render(request,'accounts/signin.html')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='signin')
def signout(request):
    logout(request)
    return redirect('ghome')

def activate(request,uidb64,token):
   try:
    uid =urlsafe_base64_decode(uidb64).decode()
    user=Account._default_manager.get(pk=uid)
   except(TypeError,ValueError,OverflowError,Account.DoesNotExist):
    user=None

   if user is not None and default_token_generator.check_token(user,token):
    user.is_active=True
    user.save()
    messages.success(request,'account activated')
    return redirect('signin')
   else:
    messages.error(request,"invalid activation link")
    return redirect('signup')


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='signin')
def dashboard(request):
    orders  =   Order.objects.order_by('-created_at').filter(user_id=request.user.id,is_ordered=True)
    orders_count=orders.count()
    context = {
        'orders_count' : orders_count
    }
    return render(request,'accounts/profile.html',context) 


def forgotPassword(request):
    if request.method=='POST':
        email= request.POST['email']
        if Account.objects.filter(email=email).exists():
            user=Account.objects.get(email__iexact=email) 
            send_forgotpassword_mail(request,user,email)
            messages.success(request,"Paswword reset email has been sent")
            return redirect('signin')
        else:
            messages.error(request,"Account doesnot exist")
            return redirect('forgotPassword')
    return render(request,'accounts/forgotPassword.html')

def resetpassword_validate(request,uidb64,token):
    try:
       uid =urlsafe_base64_decode(uidb64).decode()
       user=Account._default_manager.get(pk=uid)
    except(TypeError,ValueError,OverflowError,Account.DoesNotExist):
       user=None
       
    if user is not None and default_token_generator.check_token(user,token):
        request.session['uid'] = uid
        messages.success(request,"Please reset your password")
        return redirect('resetPassword')
    else:
        messages.error(request,"This link has been expired")
        return redirect('signin')
@login_required(login_url='signin')
def resetPassword(request):
    if request.method=='POST':
        password=request.POST['password']
        confirm_password=request.POST['confirm_password']
        if password==confirm_password:
            uid=request.session.get('uid')
            user=Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request,"Password reset successfull")
            return redirect('signin')

        else:
            messages.error(request,"Passwords do not match")
            return redirect('resetPassword')

    else:

        return render(request,'accounts/resetPassword.html')

@login_required(login_url='signin')    
def edit_profile(request):
    userprofile = get_object_or_404(EditProfile,user=request.user)
    if request.method ==  'POST':
        user_form = UserForm(request.POST,instance=request.user)
        profile_form = EditProfileForm(request.POST,instance=userprofile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,'Your Profile has been updated')
            return redirect('edit_profile')
        
    else:
        user_form=UserForm(instance=request.user)
        profile_form=EditProfileForm(instance=userprofile)

    context =   {
        'user_form' : user_form,
        'profile_form' : profile_form,
    }
    return render(request,'accounts/edit_profile.html',context)


@login_required(login_url='signin')    
def my_orders(request):
    orders  =   Order.objects.filter(user=request.user,is_ordered=True).order_by('-created_at')
    context =   {
        'orders' :orders
    }
    return render(request,'accounts/my_orders.html',context)


@login_required(login_url='signin')    
def change_password(request):
    if request.method == 'POST':
        current_password    =   request.POST['current_password']
        new_password    =   request.POST['new_password']
        confirm_password    =   request.POST['confirm_password']

        user    =   Account.objects.get(name__iexact=request.user.name)

        if new_password == confirm_password:
            success = user.check_password(current_password)
            if success:
                user.set_password(new_password)
                user.save()
                messages.success(request,'Password updated successfully')
                return redirect('change_password')
            else:
                messages.error(request,'Incorrect password')
                return redirect('change_password')
        else:
            messages.error(request,'Please enter valid password')
            return redirect('change_password')

    return render(request,'accounts/change_password.html')

@login_required(login_url='login')
def my_address(request):
   

    current_user = request.user
    address = Address.objects.filter(user=current_user)
    Address.objects.filter(user=current_user).order_by('id')


   

  
    context = {
        'address':address,
    }
    return render(request,'accounts/my_address.html',context)

@login_required(login_url='signin')
def add_address(request):
    if request.method == 'POST':
        form = AddressForm(request.POST,request.FILES,)
        if form.is_valid():
            print('form is valid')
            detail = Address()
            detail.user = request.user
            detail.name =form.cleaned_data['name']
            detail.phone =  form.cleaned_data['phone']
            detail.email =  form.cleaned_data['email']
            detail.address_line_1 =  form.cleaned_data['address_line_1']
            detail.address_line_2  = form.cleaned_data['address_line_2']
            detail.state =  form.cleaned_data['state']
            detail.city =  form.cleaned_data['city']
            detail.save()
            messages.success(request,'Address added Successfully')
            return redirect('my_address')

templates/accounts/account_verification_email.html
{% autoescape off %}

Hi {{user.name}},
Please click on below link to confirm your registration.
http://{{domain}}{% url 'activate' uidb64=uid token=token %}

if you think it's not you,please ignore this email.

Lavender Haze

{% endautoescape %}

templates/accounts/cancel_order.html
{% extends 'base.html' %}

{% block content %}
{% if messages%}
{% for message in messages %}
<div id="message" class="container">
  <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert" >
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
      {% if message.level  == DEFAULT_MESSAGE_LEVELS.ERROR %}important: {% endif %}
      {{ message }}

  </div>
</div>
{% endfor %}
{% endif %}


<div class="container" style="margin: 0 auto;width: 50%;padding: 50px;background: #f1f1f1;margin-top: 50px;margin-bottom: 50px;">
    <div class="text-center">
        <h4>Your Order has been cancelled as per your request</h4>
        <p>If you paid your amount will be refund within 1 hour.<br> If it's not refunded within time period mail to <span class="text-danger">lavdenderhaze107@gmail.com</span></p>
    </div>
    <div class="d-flex justify-content-center">
        <a href="{% url 'dashboard' %}" class="btn btn-info text-center">Back to Home</a>
    </div>
</div>


{% endblock content %}

templates/accounts/edit_address.html
{% extends 'base.html' %}
{% load static %} 
{% block content%}
 <main class="col-md-9">
      <article class="card">
      <header class="card-header">
        <strong class="d-inline-block">Add new Address</strong>
      
      </header>
      <div class="card-body">
        <div class="row"> 
        <div class="col-md-12">
                 <form action="" method="POST" enctype="multipart/form-data" >
                  {% csrf_token %}
                  <div class="form-row">
                      <div class="form-group col-md-6">
                          <label >Name</label>
                         
                         {{form.name}} 
                         
                      </div>
                     
  
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-6">
                        <label >Email</label>
                        <input type="email" name="email" value="{{form.email.value}}" maxlength="50" onkeyup="validateAddAddressEmail()" class="form-control" id="id_email">
                        	<span id="email-error"class='change'></span>
                        {% comment %} {{form.email}} {% endcomment %}

                       
                    </div>
                    <div class="form-group col-md-6">
                          <label >Phone Number</label>
                          <input type="text" name="phone" value="{{form.phone.value}}" maxlength="15" onkeyup="validateAddAddressMobilenumber()" class="form-control"  id="id_phone">
                          <span id="mobilenumber-error"class='change'></span>
                          {% comment %} {{form.phone}} {% endcomment %}
                          
                    </div>
                    <div class="form-group col-md-6">
                      <label >Address Line 1</label>
                      {{form.address_line_1}}
                     
                    </div>
                    <div class="form-group col-md-6">
                      <label >Address Line 2</label>
                      {{form.address_line_2}}
                     
                    </div>
                    <div class="form-group col-md-6">
                      <label >City</label>
                      {{form.city}}
                     
                    </div>
                    <div class="form-group col-md-6">
                      <label >State</label>
                      {{form.state}}
                     
                    </div>
                    <div class="form-group col-md-6">
                      <label >country</label>
                      {{form.country}}
                     
                    </div>
                   
                         
                  </div>
                  <input type="submit" name="" id="" value="Save" onclick="return validateAddAddresForm()" class="btn btn-dark">
                   <span id="submit-error" class="mt-2"></span>
  
                 </form>
           
        </div>
        </div> <!-- row.// -->
      </div> <!-- card-body .// -->
  
      
       <!-- table-responsive .end// -->
      </article> <!-- order-group.// --> 
    </main>



{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<style>
   label {
        margin-top: 2%;
        margin-bottom: 1%;

    }
</style>
{% if messages%}
{% for message in messages %}
<div id="message" class="container">
  <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert" >
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
      {% if message.level  == DEFAULT_MESSAGE_LEVELS.ERROR %}important: {% endif %}
      {{ message }}

  </div>
{% endfor %}
{% endif %}
 <!-- ...:::: Start Account Dashboard Section:::... -->
 <div class="account-dashboard" style="margin-top: 60px;">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3">
                <!-- Nav tabs -->
               {% include 'sidebar.html' %}
            </div>
            <div class="col-sm-12 col-md-9 col-lg-9  " style="height: 80%;">
                <!-- Tab panes -->
                <div class="tab-content dashboard_content" data-aos="fade-up" data-aos-delay="200">
                    
                   
                        <h4>Edit Profile</h4>
                        <div class="table_page table-responsive">
                           <form action="{% url 'edit_profile' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label>Name</label>
                                    <div class="form-control">{{ user_form.name }}</div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label>Phone</label>
                                    <div class="form-control">{{ user_form.phone }}</div> 
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Address_line_1</label>
                                <div class="form-control"> {{ profile_form.address_line_1}}</div>
                            </div>
                            <div class="form-group">
                                <label>Address_line_2</label>
                                <div class="form-control">{{ profile_form.address_line_2}}
                                </div></div> 
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label>City</label>
                                    <div class="form-control"> {{ profile_form.city}}</div>
                                </div>
                                <div class="form-group col-md-4">
                                    <label>State</label>
                                    <div class="form-control"> {{ profile_form.state}}</div>
                                </div>
                                <div class="form-group col-md-4">
                                    <label>Country</label>
                                    <div class="form-control">{{ profile_form.country}}</div> 
                                </div>
                            </div>
                            <input type="submit" value="Save" class="btn btn-golden" style="width: 10%;margin-top: 5%;">
                           </form>
                        </div>
                   
                   
                    
                </div>
            </div>
        </div>
    </div>
</div> <!-- ...:::: End Account Dashboard Section:::... -->




{% endblock %}

templates/accounts/forgotPassword.html
{% extends 'base.html' %}

{% block content %}
{% if messages%}
{% for message in messages %}
<div id="message" class="container">
  <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert" >
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
      {% if message.level  == DEFAULT_MESSAGE_LEVELS.ERROR %}error: {% endif %}
      {{ message }}

  </div>
</div>
{% endfor %}
{% endif %}

<div class="customer-login" style="margin-top: 50px;">
    <div class="container">
        <div class="row">
            <!--login area start-->
            <div class="col-lg-6 col-md-6">
                <div class="account_form" data-aos="fade-up" data-aos-delay="0">
                    <h3>Forgot Password</h3>
                    <form action="{% url 'forgotPassword' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-outline mb-4">
                            <input type="email" id="form3Example1cg" name="email" class="form-control form-control-lg" />
                            <label class="form-label" for="form3Example1cg">Your Email</label>
                          </div>                       
                        <div class="d-flex justify-content-center">
 
                            <button type="submit" style="background-color: #E29AD2;color: #ffff;" onmouseover="this.style.backgroundColor='#F5E5F2';" onmouseout="this.style.backgroundColor='#E29AD2';" class="btn btn-md btn-black-default-hover mb-4 text-body">Send email</button>

                          </div>
          
                          <p class="text-center text-muted mt-5 mb-0">Got Password?<a href="{% url 'signin' %}"
                              class="fw-bold text-body"><u> SignIn Here</u></a></p>



                    </form>
                </div>
            </div>
            <!--login area start-->

           
        </div>
    </div>
</div> <!-- ...:::: End Customer Login Section :::... -->

{% endblock %}

templates/accounts/my_orders.html
{% extends 'base.html' %}

{% block content %}
{% if messages%}
{% for message in messages %}
<div id="message" class="container">
  <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert" >
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
      {% if message.level  == DEFAULT_MESSAGE_LEVELS.ERROR %}important: {% endif %}
      {{ message }}

  </div>
</div>
{% endfor %}
{% endif %}
 <!-- ...:::: Start Account Dashboard Section:::... -->
 <div class="account-dashboard" style="margin-top: 60px;">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3">
                <!-- Nav tabs -->
               {% include 'sidebar.html' %}
            </div>
            <div class="col-sm-12 col-md-9 col-lg-9  " style="height: 80%;">
                <!-- Tab panes -->
                <div class="tab-content dashboard_content" data-aos="fade-up" data-aos-delay="200">
                    
                   
                        <h4>Order History</h4>
                        <div class="table_page table-responsive">
                            <table>
                                <thead>
                                    <tr style="background-color: #EAEBFF;">
                                        <th>Order No.</th>
                                        <th>Name</th>
                                        <th>Phone</th>
                                        <th>Order Total</th>
                                        <th>Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <th scope="row" ><a href="{% url 'order_detail' order.order_number %}" >{{ order.order_number }}</a></th>
                                        <td>{{ order.name }}</td>
                                        <td>{{ order.phone }}</span></td>
                                        <td>Rs.{{ order.order_total }}</td>
                                        <td>{{ order.created_at }}</a></td>
                                    </tr>
                                   {% endfor %}
                                </tbody>
                            </table>
                        </div>
                   
                   
                    
                </div>
            </div>
        </div>
    </div>
</div> <!-- ...:::: End Account Dashboard Section:::... -->




{% endblock %}

templates/accounts/resetPassword.html
{% extends 'base.html' %}


{% block content %}
{% if messages %}
{% for message in messages %}
<div id="message" class="container">
  <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert" >
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
      {% if message.level  == DEFAULT_MESSAGE_LEVELS.ERROR %}error: {% endif %}
      {{ message }}

  </div>
</div>
{% endfor %}
{% endif %}

<div class="customer-login" style="margin-top: 50px;">
    <div class="container">
        <div class="row">
            <!--login area start-->
            <div class="col-lg-6 col-md-6">
                <div class="account_form" data-aos="fade-up" data-aos-delay="0">
                    <h3>Reset Password</h3>
                    <form action="{% url 'resetPassword' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-outline mb-4">
                            <input type="password" id="form3Example4cg" name="password"  class="form-control form-control-lg" />
                            <label class="form-label" for="form3Example4cg">New Password</label>
                          </div>  
                          <div class="form-outline mb-4">
                            <input type="password" id="form3Example4cg" name="confirm_password"  class="form-control form-control-lg" />
                            <label class="form-label" for="form3Example4cg">Confirm Password</label>
                          </div>                   
                        <div class="d-flex justify-content-center">
                            <button type="submit" style="background-color: #E29AD2;color: #ffff;" onmouseover="this.style.backgroundColor='#F5E5F2';" onmouseout="this.style.backgroundColor='#E29AD2';" class="btn btn-md btn-black-default-hover mb-4 text-body">Reset Password</button>
                        </div>
          




                    </form>
                </div>
            </div>
            <!--login area start-->

           
        </div>
    </div>
</div> 




{% endblock %}

templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{user.name}},
Please click the link given below to reset your password
http://{{domain}}{% url 'resetpassword_validate' uidb64=uid token=token %}

if you think it's not you,please ignore this email.

Lavender Haze

{% endautoescape %}